name: Trigger Vercel Deploy

on:
  push:
    branches:
      - main
      - concept

jobs:
  trigger-production:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0

      - name: Trigger Vercel Production Deployment
        env:
          VERCEL_DEPLOY_HOOK: ${{ secrets.VERCEL_DEPLOY_HOOK }}
        run: |
          curl "${VERCEL_DEPLOY_HOOK}"

  trigger-concept:
    if: github.ref_name == 'concept'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Trigger Vercel Concept Deployment
        env:
          VERCEL_CONCEPT_DEPLOY_HOOK: ${{ secrets.VERCEL_CONCEPT_DEPLOY_HOOK }}
        run: |
          curl "${VERCEL_CONCEPT_DEPLOY_HOOK}"